### PR TITLE
[Cryptography] Winning Digits

### PR DESCRIPTION
**Pull request by Bomas16**
# [Winning Digits]

## Problem Statement
My friend won the powerball on Satuday, December 22, 2018 and said they would give a small part to me if I cracked thier code. 
He said something about the coordinates having been in hex, but I dont know what that could mean. 
Please help me figure out the code!
He gave me this key:
````````````````````
   0123456789ABCDEF
   ----------------
0 |QQLNULMPSKFNXGPZ 
1 |RCODMMCESJMHIFEC
2 |ZINFMYSXCBYVUHDZ
3 |IUIKQIIPFGWJZSOS
4 |JACHHCXUOJEDVXFN
5 |BXZKZDWULCVIVYQC
6 |IIILHXYZTKMICSBD
7 |ECGANTSGXPRVSJZN
8 |IDKCUIVMZZIWWMWE
9 |FSSCBMJISMNOYCQM
A |QWWZIWTJKTCSBHZR
B |GNIUBYOICISGODEA
C |LKIQYAOSXEQFPVDI
D |CCQFHEXZXNZYHSBR
E |AVVGFRAUDKADEUIW
F |BSDMZMOXJNVIAGKI

* The flag will replace x in 'bcactf{x}' *
`````````````````````
## Hints
* I think his winning digits are the key to the puzzle...
* The sides of the puzzle look like they could be a coordinate plane.

## Flag
`bcactf{XKVKUW}`

> made by: **@[Bomas16]**

### CODE REVIEW

**Comment by Bomas16** [comment]
Ignore this sorry

**Comment by edwfeng** [comment]
Please edit this to follow the style guide.

Make a directory with the problem title in the `cryptography/` directory, and place your file (titled `README.md`) there.

Please also add a solutions, in a `solutions/README.md` file.

**Comment by AidanGlickman** [comment]
> Ignore this sorry

Does this mean you don't want to submit this problem? If you do want to submit, to what Edward said above.

**Comment by Bomas16** [comment]
I submitted the problem with the correct problem after this mistake, sorry for confusion

**Pull request closed without merging**
