### PR TITLE
[Cryptography] Tricrypto

### PR DESCRIPTION
**Pull request by eruuc**

### CODE REVIEW

**Comment by edwfeng** [comment]
Could you just leave a quick writeup? (i.e. `./solutions/README.md`)

It should look something like this:
```markdown
# Tricrypto

## Procedures
<How to solve>
```

**Comment by AidanGlickman** [comment]
Hi,

Please make this problem actually possible to figure out without the hints. Either subtly make the procedure to be used clear in the problem statement, or change the procedure to make it clearer how to do the problem. Currently, if people don't use the hint they would just have to guess unless I'm missing something.

**Comment by AidanGlickman** [comment]
This problem is still flawed. Half way through the problem you get something that looks like a flag. Please change the flag to something that will not do this halfway through. In general, I think this problem needs to be improved to be accepted.

**Comment by davidionita** [comment]
I like the concept of using many different ciphers in one problem, but, in my opinion, the process of actually solving the problem is unclear. Even after I followed the write-up (I converted the number from decimal to base 8, then took that base 8 number and converted it from decimal to base 16, then took that base 16 number and decoded it using ROT 13) and I still couldn't find the flag (I got this weird string: "4N41S3N13349046Q3RPQ").  I suggest you try making the process for solving the problem more apparent in your problem statement through word-play or some sort of riddle.  Please check this.

**Pull request closed without merging**
